export { default as App } from './App/App'
export { default as Cadastro } from './Cadastro/Cadastro'
export { default as Login } from './Login/Login'
export { default as Home } from './Home/Home'
export { default as Planos } from './Planos/Planos'
export { default as Contato } from './Contato/Contato'
export { default as Pagamento } from './Pagamento/Pagamento'
export { default as HomeAfter } from './HomeAfter/HomeAfter'
export { default as EditarPerfil } from './EditarPerfil/EditarPerfil'
export { default as PlanosAfter } from './PlanosAfter/PlanosAfter'
export { default as Cancelar } from './Cancelar/Cancelar'

