export { default as App } from './App/App'
export { default as Cadastro } from './Cadastro/Cadastro'
export { default as Livro } from './Livro/Livro'
export { default as Login } from './Login/Login'
export { default as Home } from './Home/Home'
export { default as Planos } from './Planos/Planos'
export { default as Contato } from './Contato/Contato'
export { default as Pagamento } from './Pagamento/Pagamento'
export { default as HomeAfter } from './HomeAfter/HomeAfter'

